=== phac-nml/irida-next/config/schemas/pipelines_schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "url": {
        "type": "string"
      },
      "name": {
        "type": "string"
      },
      "description": {
        "anyOf": [
          {
            "type": "string"
          },
          {
            "type": "object"
          }
        ]
      },
      "overrides": {
        "$ref": "#/$defs/overrides"
      },
      "versions": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "name": {
              "type": "string"
            },
            "automatable": {
              "type": "boolean"
            },
            "overrides": {
              "$ref": "#/$defs/overrides"
            }
          },
          "required": [
            "name"
          ]
        }
      }
    },
    "required": [
      "url",
      "name",
      "description",
      "versions"
    ]
  },
  "$defs": {
    "overrides": {
      "type": "object",
      "properties": {
        "definitions": {
          "type": "object"
        }
      }
    }
  }
}

=== phac-nml/irida-next/test/config/pipelines/pipelines.json
[
  {
    "url": "https://github.com/phac-nml/iridanextexample",
    "name": "phac-nml/iridanextexample",
    "description": "IRIDA Next Example Pipeline",
    "versions": [
      {
        "name": "1.0.2",
        "automatable": true
      },
      {
        "name": "1.0.1",
        "executable": true
      },
      {
        "name": "1.0.0",
        "executable": false
      }
    ]
  }
]
